feature #59-2: added option for creating Group Member by UserName
crossplane-contrib/provider-gitlab pull request #103
Opened 2023-08-21 10:29 UTC by IntaSlapna

### Description of your changes

Issue #59 - part 2: added option for creating Group Member by UserName.

Needed label "braking-change" as well, because MemberParameters.UserID changed from int to *int. 

-->
Fixes #59 

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Unit-tests used. `make reviewable test` PASS. 

[contribution process]: https://git.io/fj2m9

2023-09-04 14:10 UTC, MisterMX requested changes

2023-09-05 13:34 UTC, IntaSlapna commented on Makefile
> -
I suppose there was GO_REQUIRED_VERSION := 1.20 
Which we don't push, right?

2023-09-05 13:43 UTC, IntaSlapna commented on apis/projects/v1alpha1/member_type.go
> +	UserID *int `json:"userId,omitempty"`
changed

2023-09-05 14:53 UTC, MisterMX commented on pkg/clients/users/user.go
> +		return nil, errors.New(errFetchFailed)
But if we don't receive the correct user ID shouldn't `len(userArr) == 0`? And if there is any element in the array then it means success?

2023-09-05 14:54 UTC, MisterMX commented on Makefile
> -
No, as the diff shows, there was just an empty line which got removed. But that is not a necessary change.

2023-09-06 07:18 UTC, IntaSlapna commented on pkg/clients/users/user.go
> +		return nil, errors.New(errFetchFailed)
It means that it is not needed double check? 
I will take out this "if" then.

2023-09-06 07:21 UTC, IntaSlapna commented on pkg/clients/users/user.go
> +		return nil, errors.New(errFetchFailed)
And yes, the idea was if there is only one element in array it means that we successfully have matched user by username and can extract usedID.

2023-09-06 09:20 UTC, MisterMX commented on pkg/clients/users/user.go
> +		return nil, errors.New(errFetchFailed)
Sounds good

2023-09-12 12:02 UTC, MisterMX approved these changes
LGTM. Thank you very much for your contribution @IntaSlapna!

2023-09-12 12:02 UTC, merged