feat: Upgrade to crossplane-runtime `v1.14.4`
crossplane-contrib/provider-gitlab pull request #119
Opened 2024-02-01 14:25 UTC by MisterMX

### Description of your changes

Add support for store configs.
Add support for management policies.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

n.a. since no changes in the controller logic have been made. Only Setup has been adjusted.

[contribution process]: https://git.io/fj2m9

2024-02-02 16:59 UTC, somebadcode commented on .github/workflows/ci.yaml
> +  GOLANGCI_VERSION: 'v1.54.0'
Shouldn't this be bumped to `v1.55.2`?

2024-02-09 09:44 UTC, janwillies requested changes
Thanks @MisterMX! Looks good to me, but before merging please run `s/aws/gitlab/`

2024-02-14 19:02 UTC, janwillies requested changes
Some of `aws` still present :)

2024-02-14 19:02 UTC, janwillies commented on apis/v1alpha1/doc.go
> +// +groupName=aws.crossplane.io
These should be gitlab and a couple others too

2024-02-21 10:26 UTC, janwillies approved these changes
LGTM, thanks @MisterMX!

2024-02-21 10:26 UTC, merged