feat!: deprecate emails_disabled in favor of emails_enabled
crossplane-contrib/provider-gitlab pull request #154
Opened 2024-08-05 09:51 UTC by dariozachow

### Description of your changes

This PR fixes the Issue with Gitlab 16, where emails_disabled has been renamed to emails_enabled  on groups.
This is a breaking change even though It should have been none breaking as discussed here.
But when implementing the changes it felt awkward to work with 2 fields witch are dependend on each other.
This makes a clean representation of the actual Gitlab-API.

The go-gitlab dependency has been updated to the latest version as well.

Fixes #141 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Tests have been updated to test for emailsEnabled instead of emailsDisabled

[contribution process]: https://git.io/fj2m9

2024-08-05 11:32 UTC, dariozachow commented
@MisterMX @janwillies

2024-08-20 08:39 UTC, MisterMX requested changes
LGTM so far. However, we should always provide backward compatibility if possible to provide a clear migration path for users.

2024-08-20 08:39 UTC, MisterMX commented on apis/groups/v1alpha1/group_types.go
> +	EmailsEnabled *bool `json:"emailsEnabled,omitempty"`
To ensure backwards compatibility we should keep `EmailsDisabled` as a deprecated property and add `EmailsEnabled` as the new recommended option.

Similar to what is described in https://github.com/crossplane-contrib/provider-gitlab/issues/141#issuecomment-2247099937 the field `EmailsEnabled` should be late-initialized during observe (pseudocode):

```go
cr.Spec.ForProvider.EmailsEnabled = LateInitialize(cr.Spec.ForProvider.EmailsEnabled, cr.Spec.ForProvider.EmailsDisabled)
````

And after that `EmailsEnabled` can be used throughout the rest of the controller.

2024-08-21 09:38 UTC, MisterMX requested changes

2024-08-21 09:38 UTC, MisterMX commented on apis/groups/v1alpha1/group_types.go
>  	EmailsDisabled *bool `json:"emailsDisabled,omitempty"`
Deprecation marker should be in a new line (ref. https://go.dev/blog/godoc):

```suggestion
	// Disable email notifications.
	//
	// Deprecated: Use emailsEnabled instead.
	// +optional
	EmailsDisabled *bool `json:"emailsDisabled,omitempty"`
```

2024-08-21 12:46 UTC, merged