Group Resource
crossplane-contrib/provider-gitlab pull request #19
Opened 2021-04-13 14:32 UTC by Stanislav2017

### Description of your changes

Created api for working with Gitlab group resource

Created new api
/provider-gitlab/apis/groups/v1alpha1

Created client
/provider-gitlab/pkg/clients/groups/group.go 

Created controller
/provider-gitlab/pkg/controller/groups/group.g

Created group.yaml
/provider-gitlab/examples/groups/group.yaml

Fixes #

Added new schema
/provider-gitlab/apis/gitlab.go

Added new func
/provider-gitlab/pkg/clients/gitlab.go

Added new controller
/provider-gitlab/pkg/controller/gitlab.go

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

I tested this code on my machine and wrote tests to test all the code I wrote
/provider-gitlab/pkg/clients/groups/group_test.go
/provider-gitlab/pkg/controller/groups/group_test.go

[contribution process]: https://git.io/fj2m9

2021-04-16 09:09 UTC, janwillies requested changes
Hey @Stanislav2017, thanks for the contribution! Some small comments, but looking good already!

2021-04-16 09:11 UTC, janwillies commented
Please also squash your commits into a single one, you can read about it here: https://www.internalpointers.com/post/squash-commits-into-one-git

2021-04-16 10:58 UTC, Stanislav2017 commented on pkg/controller/groups/group.go
> +func LateInitialize(in *v1alpha1.GroupParameters, group *gitlab.Group) { // nolint:gocyclo
I think no. I will rename this method to lateInitialize

2021-04-16 10:59 UTC, Stanislav2017 commented on pkg/controller/groups/group.go
> +// IsGroupUpToDate checks whether there is a change in any of the modifiable fields.
I think no. I will rename this method to isGroupUpToDate

2021-04-27 11:00 UTC, janwillies approved these changes
this looks very good, thanks a lot @Stanislav2017! FWIW it has been reviewed in https://github.com/crossplane-contrib/provider-gitlab/pull/18 and in a now-deleted repo as well.

2021-04-27 11:00 UTC, merged