Implement Deploy token for group
crossplane-contrib/provider-gitlab pull request #51
Opened 2021-09-28 09:49 UTC by Stanislav2017

Signed-off-by: Stanislav2017 <stanislavchichek@gmail.com>

### Description of your changes

Fixes #

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

2021-09-29 11:36 UTC, janwillies requested changes
Thanks a lot @Stanislav2017! Some small nits only.

I see some changes to the `build` submodule, I assume you updated it?

2021-09-29 11:36 UTC, janwillies commented on examples/groups/group.yaml
> +    crossplane.io/external-name: "12591945"
I believe this was added by accident?

2021-09-29 11:36 UTC, janwillies commented on examples/groups/group.yaml
> +    # parentIdRef:
I believe this was added by accident?

2021-09-29 11:36 UTC, janwillies commented on examples/projects/project.yaml
> +  importUrlSecretRef:
I believe this was added by accident?

2021-09-29 11:36 UTC, janwillies commented on pkg/controller/groups/deploytokens/controller.go
> +Copyright 2020 The Crossplane Authors.
2021

2021-09-29 14:00 UTC, Stanislav2017 commented
> Thanks a lot @Stanislav2017! Some small nits only.
> 
> I see some changes to the `build` submodule, I assume you updated it?

No, I just did a rebase with master

2021-12-10 15:59 UTC, Benedikt1992 commented on pkg/controller/groups/deploytokens/controller.go
> +		*cr.Spec.ForProvider.GroupID,
I get a nil pointer exception if I leave the group field empty (which is a optional field)

2021-12-14 16:01 UTC, Benedikt1992 commented on pkg/controller/groups/deploytokens/controller.go
> +		*cr.Spec.ForProvider.GroupID,
Implemented in #53

2021-12-14 16:02 UTC, Benedikt1992 commented
PR continued in #53

2021-12-15 09:48 UTC, closed without merging