feat(accesstoken): Add project access token resource
crossplane-contrib/provider-gitlab pull request #82
Opened 2023-07-25 08:56 UTC by IntaSlapna

### Description of your changes

Fixes #58

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

2023-07-25 13:14 UTC, MisterMX requested changes

2023-07-26 11:55 UTC, IntaSlapna commented on pkg/controller/projects/accesstokens/controller.go
> +	cr.Status.AtProvider = v1alpha1.AccessTokenObservation{}
deleted

2023-07-26 12:00 UTC, IntaSlapna commented on pkg/controller/projects/accesstokens/controller.go
> +func findAccessToken(accessTokenID int, accessTokens []*gitlab.ProjectAccessToken) *gitlab.ProjectAccessToken {
deleted

2023-07-26 12:01 UTC, IntaSlapna commented on pkg/controller/projects/accesstokens/controller.go
> +func newAccessTokenClient(cfg clients.Config) gitlab.ProjectAccessTokensService {
deleted

2023-07-26 12:08 UTC, IntaSlapna commented on pkg/controller/projects/accesstokens/controller.go
> +func isErrorProjectAccessTokenNotFound(err error) bool {
Deleted from clients/projects/accesstoken.go, left in controller.go

2023-07-26 12:19 UTC, IntaSlapna commented on pkg/controller/projects/accesstokens/controller.go
> +func isErrorProjectAccessTokenNotFound(err error) bool {
Deleted and imported from clients/projects.

2023-07-26 15:36 UTC, MisterMX requested changes

2023-07-31 09:53 UTC, MisterMX approved these changes
LGTM. Thank you very much for your contribution @IntaSlapna!

2023-07-31 09:53 UTC, merged